from typing import Dict, Any
from core.ingestion.base import BaseIngestionAdapter
from core.models.alert import SystemAlert, Severity

class DaemonAdapter(BaseIngestionAdapter):
    """
    Adapter for our native daemon.py 'phone home' events.
    Expected format: 
    {
        "service_name": "...",
        "severity": "CRITICAL",
        "error_code": "...",
        "message": "..."
    }
    """
    @property
    def source_name(self) -> str:
        return "daemon"

    def normalize(self, payload: Dict[str, Any]) -> SystemAlert:
        # Our daemon already sends data in a close-to-final format
        return SystemAlert(
            alert_id=payload.get("alert_id", "DAEMON-AUTO"), # ID will be auto-generated by Manager if missing
            service_name=payload.get("service_name", "unknown-daemon-service"),
            severity=Severity(payload.get("severity", "ERROR").upper()),
            error_code=payload.get("error_code", "DAEMON_REPORT"),
            message=payload.get("message", "Daemon reported an infrastructure event."),
            metadata=payload.get("metadata", {})
        )
